server:
  port: 8080
spring:
  application:
    name: scheduler-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: test
    password: test123
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

#mapper 别名扫描
mybatis:
  type-aliases-package: com.ly.domain.entity
  #mapper.xml文件位置,如果没有映射文件，请注释掉
  mapper-locations: classpath:mappers/*.xml
  #数据库类型
  configuration.database-id: mysql
  #自动驼峰转换
  configuration.map-underscore-to-camel-case: true

